[package]
name = "suborbital_demo"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
publish = false
rust-version = "1.56.0"

[workspace]

[dependencies]
ockam = { path = "../../../implementations/rust/ockam/ockam" }
